### ISSUE TITLE
java.lang.NoSuchMethodError: scala.runtime.RichInt.until(I)Lscala/collection/immutable/Range$ByOne;

### ISSUE THREAD

**Issue by jared1** [brightcove-archive/ooyala_metrics-storm#6]
I'm trying to use a Storm topology with a spout that connects to Kafka. Not including the metrics_storm code on my classpath, my topology runs with no issues, but once I include metrics_storm, I get the following error when the topology runs:

java.lang.NoSuchMethodError: scala.runtime.RichInt.until(I)Lscala/collection/immutable/Range$ByOne;

Are there any conflicts with the metrics_storm code and the Kafka API?

Thanks,
-Jared

**Comment by velvia** [comment]
Hmm....   what version of Kafka is included in Storm?  Which version of
Storm are you running?

On Wed, Jan 29, 2014 at 2:12 PM, jared1 notifications@github.com wrote:

> I'm trying to use a Storm topology with a spout that connects to Kafka.
> Not including the metrics_storm code on my classpath, my topology runs with
> no issues, but once I include metrics_storm, I get the following error when
> the topology runs:
> 
> java.lang.NoSuchMethodError:
> scala.runtime.RichInt.until(I)Lscala/collection/immutable/Range$ByOne;
> 
> Are there any conflicts with the metrics_storm code and the Kafka API?
> 
> Thanks,
> -Jared
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/metrics_storm/issues/6
> .

## 

## 

Evan Chan
Staff Engineer
ev@ooyala.com  |

http://www.ooyala.com/
http://www.facebook.com/ooyalahttp://www.linkedin.com/company/ooyalahttp://www.twitter.com/ooyala

**Comment by jared1** [comment]
I'm using Storm 0.9.0.1 with Kafka 0.7.2.

-Jared

**Comment by velvia** [comment]
Hm.  I believe the problem is that Kafka 0.7.2 uses Scala 2.8, but our
library uses Scala 2.9.
The easiest solution for you would be to recompile metrics_storm for Scala
2.8.  I haven't tried it, don't expect any major hiccups.
The alternative is to bundle in a Kafka-client package that uses Scala 2.9.
  That is what we use;  I can probably point you to it if you incline.
 (The actual Kafka server itself can stay at the default Scala version;  it
only matters the client code that is packaged together with metrics_storm).

On Thu, Jan 30, 2014 at 1:11 PM, jared1 notifications@github.com wrote:

> I'm using Storm 0.9.0.1 with Kafka 0.7.2.
> 
> -Jared
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ooyala/metrics_storm/issues/6#issuecomment-33733804
> .

## 

## 

Evan Chan
Staff Engineer
ev@ooyala.com  |

http://www.ooyala.com/
http://www.facebook.com/ooyalahttp://www.linkedin.com/company/ooyalahttp://www.twitter.com/ooyala

**Comment by jared1** [comment]
Ah, yes, that looks like that was the problem. After recompiling metrics_storm for 2.8, I'm no longer getting any errors; the only small hiccup in doing that was the scala.sys.process library in the test code is not supported in 2.8, but everything seems to be working fine when testing with my deployed Storm topology.

Thanks again!
